name: flutter_full_pdf_viewer_example
description: Demonstrates how to use the flutter_full_pdf_viewer plugin.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  path_provider:
  cupertino_icons:
  flutter_full_pdf_viewer:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true